apiVersion: v1
kind: Service 
metadata:
  name: flask
spec:
  selector:
    app: app=flask
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask
  type: LoadBalancer
